In [1]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import sys

In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import LabelEncoder ,OneHotEncoder

In [3]:
dataset = pd.read_csv("dataset.csv");

In [4]:
df1 = pd.DataFrame(dataset)
X = df1.iloc[:,1:4]
Y = df1.iloc[:,0]
features = np.array(X.columns)
# features
np.array(X)

array([['itching', 'skin_rash', 'nodal_skin_eruptions'],
       ['skin_rash', 'nodal_skin_eruptions', 'dischromic _patches'],
       ['itching', 'nodal_skin_eruptions', 'dischromic _patches'],
       ...,
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]], dtype=object)

In [5]:
LabelEncoder_Y= LabelEncoder()
Y= LabelEncoder_Y.fit_transform(Y)
np.amin(Y)

0

In [6]:
# LabelEncoder_X= LabelEncoder()
# # X= np.array(X)
# # X = LabelEncoder_X.fit_transform(X[0])
# for i in range(0,3):
#     X.loc[:,features[i]]= LabelEncoder_X.fit_transform(X.iloc[:,i])
# print(X.shape)
# X
# np.array(X_train)

In [7]:
# after_encoding = pd.get_dummies(X,columns=features)
# X=after_encoding 
# X
enc = OneHotEncoder(handle_unknown='ignore').fit(X)
X = enc.transform(X).toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [8]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=5)
# after_one_hot_encoding_X_train = pd.get_dummies(X_train,columns=features)
# X_train = after_one_hot_encoding_X_train
# after_one_hot_encoding_X_test = pd.get_dummies(X_test,columns=features)
# X_test = after_one_hot_encoding_X_test
# from sklearn.preprocessing import StandardScaler
# sc_X = StandardScaler()
# X_train = sc_X.fit_transform(X_train)
# X_test = sc_X.fit_transform(X_test)

In [9]:
X_train = np.array(X_train)
X_test = np.array(X_test)
Y_train = np.array(Y_train)
Y_test = np.array(Y_test)


In [10]:
Y_test

array([41, 21, 13, ..., 41, 33, 36])

In [11]:
model = keras.Sequential([
    keras.layers.Dense(900,activation = "relu"),
    keras.layers.Dense(500,activation = "relu"),
    tf.keras.layers.Dense(42,activation = 'softmax')
    # tried with sigmoid as well, but the results are quite same.
])
model.compile(
    optimizer ='adam',
    loss = 'sparse_categorical_crossentropy',
    metrics =['accuracy']
)
model.fit(X_train,Y_train,epochs = 5)

Epoch 1/5
134/134 [==============================] - 1s 5ms/step - loss: 0.8011 - accuracy: 0.8640
Epoch 2/5
134/134 [==============================] - 1s 5ms/step - loss: 0.1130 - accuracy: 0.9494
Epoch 3/5
134/134 [==============================] - 1s 5ms/step - loss: 0.1034 - accuracy: 0.9510
Epoch 4/5
134/134 [==============================] - 1s 5ms/step - loss: 0.1046 - accuracy: 0.9531
Epoch 5/5
134/134 [==============================] - 1s 5ms/step - loss: 0.1004 - accuracy: 0.9489


In [12]:
model.evaluate(X_test,Y_test)

34/34 [==============================] - 0s 2ms/step - loss: 0.0875 - accuracy: 0.9531


[0.0875338464975357, 0.9531396627426147]

In [13]:
Y_pred = model.predict(X_test)
Y_pred.shape

(1067, 42)

In [14]:
Y_pred_values =[np.argmax(i) for i in Y_pred]
Y_pred_values = np.array(Y_pred_values)
Y_pred_values

array([41, 22, 13, ..., 41, 33, 37], dtype=int64)

In [15]:
tf.math.confusion_matrix(labels=Y_test,predictions=Y_pred_values)

<tf.Tensor: shape=(42, 42), dtype=int32, numpy=
array([[20,  0,  0, ...,  0,  0,  0],
       [ 0, 23,  0, ...,  0,  0,  0],
       [ 0,  0, 35, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 25,  0,  0],
       [ 0,  0,  0, ...,  0, 22,  0],
       [ 0,  0,  0, ...,  0,  0, 73]])>

In [16]:
print(LabelEncoder_Y.inverse_transform([15]))

['Fungal infection']


In [17]:
## for mongo db to puthon connection using pymongo
import pymongo as pm

myconnection = pm.MongoClient("mongodb://localhost:27017/")

mydb = myconnection["health_db"]
mycol = mydb["Symptoms"]

symptoms_dict_array=[]
for x in mycol.find({},{"_id":0}):
  symptoms_dict_array.append(x)
symptoms_array = np.array(list(symptoms_dict_array[0].values()))
print(symptoms_array)
#['itching', ' skin_rash', ' dischromic _patches']

newvalues_X = enc.transform([symptoms_array]).toarray()
newvalues_X

['vomiting' 'loss_of_appetite' 'passage_of_gases']


C:\Users\arcyj\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
# newvalues_X = enc.transform([['itching', ' skin_rash', ' dischromic _patches']]).toarray()
# newvalues_X.shape

In [19]:
Y_pred_new = model.predict(newvalues_X)

In [20]:
Y_pred_values_new =[np.argmax(i) for i in Y_pred_new]
Y_pred_values_new = np.array(Y_pred_values_new)
Y_pred_values_new[0]

33

In [21]:
output_value = LabelEncoder_Y.inverse_transform([Y_pred_values_new[0]])[0]
#print(LabelEncoder_Y.inverse_transform([Y_pred_values_new[0]]))
print(output_value)

Peptic ulcer diseae


In [22]:
dataset2 = pd.read_csv("symptom_Description.csv")
dataset2.index = dataset2.loc[:,"Disease"]

In [23]:
disease_description = dataset2.loc[[output_value],"Description"].to_numpy()
disease_description

array(['Peptic ulcer disease (PUD) is a break in the inner lining of the stomach, the first part of the small intestine, or sometimes the lower esophagus. An ulcer in the stomach is called a gastric ulcer, while one in the first part of the intestines is a duodenal ulcer.'],
      dtype=object)

In [24]:
dataset3 = pd.read_csv("symptom_precaution.csv")
dataset3.index = dataset3.loc[:,"Disease"]

In [25]:
disease_precaution = dataset3.loc[[output_value],["Precaution_1","Precaution_2","Precaution_3","Precaution_4"]].to_numpy()
disease_precaution = disease_precaution.reshape(-1)
disease_precaution

array(['avoid fatty spicy food', 'consume probiotic food',
       'eliminate milk', 'limit alcohol'], dtype=object)

In [26]:
output_data_dictionary = {
    "$set":{
    "description": disease_description[0],
    "precautions_1": disease_precaution[0],
    "precautions_2": disease_precaution[1],
    "precautions_3": disease_precaution[2],
    "precautions_4": disease_precaution[3]
    }
}

insertion_id = {
    "_id":sys.argv[1]
}
print(insertion_id)
mycol.update_one(insertion_id,output_data_dictionary)